DAST rescan
HCL-TECH-SOFTWARE/appscan-sdk pull request #176
Opened 2024-11-26 13:25 UTC by vishalhcl-5960

Implementation of rescan functionality for the dynamic scans.

2024-12-03 16:17 UTC, mattmurp requested changes

2024-12-03 16:17 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static String getA360Version(IAuthenticationProvider provider) {
There are a number of problems with this method:

1. The javadoc comment is not accurate.
2. The method name should just be getServiceVersion, not getA360Version.
3. We shouldn't need a valid token to check the service version.
4. We shouldn't need the authentication header.
5. You should use "body.getString()" as opposed to casting.
6. The comment in the catch block doesn't make sense.

2024-12-03 16:17 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONArray getExecutionDetails(String scanId, IAuthenticationProvider provider) {
Why are there DAST specific checks here? The "IsValidForIncremental" property would only be true for DAST scans, but what if someone called this method for a SAST or SCA scan? This seems like a very specific method that is being added as a general utility method.

2024-12-03 16:17 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONObject scanSpecificDetails(String type, String scanId, IAuthenticationProvider provider) {
The name of this method should be an action, like "getScanDetails()".

2024-12-04 07:36 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ArchiveUtil.java
> -        if (fileToZip.getName().startsWith(".")) {
This change is being made to include the ".git" folder when creating a zip archive of the parent folder from a Git repository. 
Task details: https://jira02.hclpnp.com/browse/ASA-9830

2024-12-04 12:08 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONObject scanSpecificDetails(String type, String scanId, IAuthenticationProvider provider) {
Sure, renaming the method to "getScanDetails()".

2024-12-04 12:50 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONArray getExecutionDetails(String scanId, IAuthenticationProvider provider) {
This method is used to fetch the "executionIds" which helps to fill the base scan dropdown field of incremental scan. I am renaming this method to "getBaseScanDetails" for better understanding.

2024-12-04 14:10 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static String getA360Version(IAuthenticationProvider provider) {
Sure, Made the suggested changes.

2024-12-04 19:46 UTC, mattmurp requested changes

2024-12-04 19:46 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONObject getScanDetails(String type, String scanId, IAuthenticationProvider provider) {
What's the need for the addition of this method here when we already have the CloudScanServiceProvider that does the same thing?

2024-12-04 19:46 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONArray getBaseScanDetails(String scanId, IAuthenticationProvider provider) {
This method would be better as a part of the IScanServiceProvider (i.e. CloudScanServiceProvider) as opposed to being added as a utility method here.

2024-12-04 19:46 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static void updateScanData(Map<String, String> params, String scanId, IAuthenticationProvider provider, IProgress progress) {
Similar to the other comments, it's not clear why this is being added as a utility method, as opposed to the IScanServiceProvider that performs related functions.

2024-12-05 12:19 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONObject getScanDetails(String type, String scanId, IAuthenticationProvider provider) {
There are difference in the APIs. The method which is there in the CloudScanServiceProvider call the general API "GET /api/v4/Scans $filter=Id eq <scanId>" to fetch the scan details but new method of ServiceUtil calls the scan specific API "GET /api/v4/<scanType>/<scanId>".
For scanId validation, We want to get the value of the "gitRepoPlatform" parameter which is not present in the respeonse of general API.

2024-12-05 12:23 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static void updateScanData(Map<String, String> params, String scanId, IAuthenticationProvider provider, IProgress progress) {
Okay, I will move it to the cloudScanServiceProvider class.

2024-12-06 13:35 UTC, vishalhcl-5960 commented on src/main/java/com/hcl/appscan/sdk/utils/ServiceUtil.java
> +    public static JSONObject getScanDetails(String type, String scanId, IAuthenticationProvider provider) {
Matt, Should we move this new method into CloudScanServiceProvider class as it is perform related function?

2024-12-16 13:18 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/scan/CloudScanServiceProvider.java
> +	public void updateScanData(Map<String, String> params, String scanId, IAuthenticationProvider provider, IProgress progress) {
Why does this method take an IAuthenticationProvider and an IProgress as parameters when there are already member variables of those types?

2024-12-16 13:41 UTC, mattmurp approved these changes

2024-12-16 13:59 UTC, merged