ASA-4007
HCL-TECH-SOFTWARE/appscan-sdk pull request #70
Opened 2022-06-29 11:52 UTC by vishalhcl-5960

contains changes of the implementation of "login required: Sequence file" option.

2022-06-29 13:54 UTC, mattmurp requested changes

2022-06-29 13:54 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/scanners/dynamic/DASTScan.java
> +		if (scanLoginType.equals("Manual")) {
Is there guaranteed to be a property LOGIN_TYPE? Switching this check to the following would avoid a potential NPE if the LOGIN_TYPE property doesn't exist:
`if("Manual".equals(scanLoginType)) {`

2022-06-29 13:54 UTC, mattmurp commented on src/main/java/com/hcl/appscan/sdk/scanners/ASoCScan.java
> +	private String m_trafficFileId;
Is this variable needed? I don't see it used anywhere. If it is required it only applies to DAST scans, so it should be on the DASTScan class, not the ASoCScan class.

2022-07-03 17:25 UTC, vishalhcl commented on src/main/java/com/hcl/appscan/sdk/scanners/ASoCScan.java
> +	private String m_trafficFileId;
Yeah Matt, We are not using this anywhere.

2022-07-03 17:25 UTC, vishalhcl commented on src/main/java/com/hcl/appscan/sdk/scanners/dynamic/DASTScan.java
> +		if (scanLoginType.equals("Manual")) {
Made the changes accordingly.

2022-07-05 13:08 UTC, mattmurp approved these changes

2022-07-05 13:08 UTC, merged