ASA-6202
HCL-TECH-SOFTWARE/appscan-sdk pull request #85
Opened 2023-05-15 15:38 UTC by vishalhcl-5960

"Source Code Only" option support

2023-05-15 15:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/HCL-TECH-SOFTWARE/appscan-sdk?pullRequest=85) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/HCL-TECH-SOFTWARE/appscan-sdk?pullRequest=85) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/HCL-TECH-SOFTWARE/appscan-sdk?pullRequest=85) it.</sub>

2023-05-15 15:57 UTC, mattmurp requested changes
Looks good. Can you fix the indentation of the new code so it matches what's already present?

2023-05-18 06:04 UTC, kripajoym approved these changes

2023-05-18 14:33 UTC, mattmurp approved these changes

2023-05-18 14:34 UTC, merged